# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Plugins
plugins: [jekyll-watch, jekyll-paginate, webrick]

# Setup
title:            Henry Barreto's Blog
tagline:          "Henry Barreto's Blog"
description:      "Software Developer, Linux user and Open-source enthusiast."
url:              https://henrybarreto.dev
baseurl:          /

author:
  name:   "Henry Barreto"
  email:  "me@henrybarreto.dev"

paginate:   5

# Custom vars
