# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Plugins
plugins: [jekyll-watch, jekyll-paginate, webrick]

# Setup
title:            Henry Barreto's Blog
description:      "I am a software developer specializing in Back-end development, with a keen interest in networking programming."
url:              https://henrybarreto.dev
baseurl:          /

author:
  name:   "Henry Barreto"
  email:  "me@henrybarreto.dev"

paginate:   5

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : [
  "Dockerfile",
  "Makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/"
]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Custom vars

## Google Analytics
google_analytics: G-LYPXDBSB22
